#!/usr/local/bin/python
import argparse


def function1():
    print "Function 1"


def function2(what_to_type):
    with open('mconf.txt', 'w+') as f:
        f.write("This is the first line of my file: {0}".format(what_to_type))

    print "Function 2"


def lutin():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--option1',
        type=str,
        help='Nothing',
        default=None)
    parser.add_argument(
        '--option2',
        type=str,
        help='Nothing',
        default=None)

    args = parser.parse_args()

    if args.option1:
        function1()
    elif args.option2:
        function2(args.option2)


if __name__ == '__main__':
    lutin()
